version: "3.9"
services:
  #frontend da aplicação
  frontend:
    build:
      context: ./web-quiz
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
    ports:
      - 4200:4200
    depends_on:
      - backend
    networks:
      - dbl-network

  # backend da aplicação
  backend:
    build:
      context: ./api-quiz
      dockerfile: Dockerfile
    restart: always
    environment:
      TZ: America/Sao_Paulo
      SPRING.DATASOURCE.URL: jdbc:postgresql://postgres-db:5432/quiz-db
      SPRING.DATASOURCE.USERNAME: postgres
      SPRING.DATASOURCE.PASSWORD: postgres
    ports:
      - 8080:8080
    command: mvn spring-boot:run
    depends_on:
      - postgres-db
    networks:
      - dbl-network

  # banco de dados postgres para o backend
  postgres-db:
    image: postgres:16.2
    restart: always
    environment:
      TZ: America/Sao_Paulo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: quiz-db
      POSTGRES_HOST_AUTH_METHOD: "md5"
    ports:
      - 5433:5432
    expose:
      - 5432
    networks:
      - dbl-network

# networks para comunicação entre os containers
networks:
  dbl-network:
    driver: bridge
